#!/bin/bash
mv /opt/HBJson/log/lastheard.log /opt/HBJson/log/lastheard.log.save
/usr/bin/tail -150 /opt/HBJson/log/lastheard.log.save > /opt/HBJson/log/lastheard.log
mv /opt/HBJson/log/lastheard.log /opt/HBjson/log/lastheard.log.save
/usr/bin/tail -150 /opt/HBJson/log/lastheard.log.save > /opt/HBJson/log/lastheard.log
